import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Music Carnival",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Image Overlay */}
        <div className="image-overlay"></div>

        {/* Main Content */}
        {children}
      </body>
    </html>
  );
}
